### ISSUE TITLE
Any reason not using priority_queue for eventQueue in engine.cc?

### ISSUE THREAD

**Issue by zinechant** [SimpleSSD/SimpleSSD-Standalone#26]
Currently eventQueue is std::list.
insert and erase are O(N).
priority queue would make them O(logN)

Is it that queue wouldn't be very long any way?

**Comment by kukdh1** [comment]
Hi,

I did not use the C++'s `priority_queue` because it does not support to remove arbitrary element other than the "root".
(This feature is merely used but should be supported when the `remoteEvent()` is called)

Also, I have following observations to not implement custom priority queue:
- Events are inserted in near future (no need to search until the end of list).
- Maximum length of event queue is less than 10, and in average, less than 5.

Thanks.
